/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Entries = {
  /**
   * ID of the entry returned from miHoYo API
   */
  id: string;
  /**
   * Item type text returned from miHoYo API
   */
  itemType: string;
  /**
   * Language code returned from miHoYo API
   */
  lang: string;
  /**
   * Item name text
   */
  name: string;
  /**
   * Gacha type ID to send request to query
   */
  queryGachaType: string;
  /**
   * Actual gacha type of the entry
   */
  gachaType: string;
  /**
   * Typically this is a rarity number
   */
  rankType: string;
  time: string;
  uid: string;
}[];

export interface GachaExport {
  schemaVersion: 1;
  exportedAt: string;
  games: {
    genshin: Entries;
    hsr: Entries;
    zzz: Entries;
  };
}
