/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Uigf42 {
  info: {
    /**
     * The timestamp of the export, in seconds
     */
    export_timestamp: string | number;
    /**
     * The name of the application that exported the archive
     */
    export_app: string;
    /**
     * The version of the app that exported the archive
     */
    export_app_version: string;
    /**
     * The UIGF version of the exported archive, formatted as 'v{major}.{minor}', e.g., v4.0
     */
    version: string;
    [k: string]: unknown;
  };
  hk4e?: {
    /**
     * UID
     */
    uid: string | number;
    /**
     * Time zone offset
     */
    timezone: number;
    /**
     * Language code
     */
    lang?:
      | "de-de"
      | "en-us"
      | "es-es"
      | "fr-fr"
      | "id-id"
      | "it-it"
      | "ja-jp"
      | "ko-kr"
      | "pt-pt"
      | "ru-ru"
      | "th-th"
      | "tr-tr"
      | "vi-vn"
      | "zh-cn"
      | "zh-tw";
    list: {
      /**
       * UIGF gacha type, used to distinguish between different gacha types that have the same pity calculation
       */
      uigf_gacha_type: "100" | "200" | "301" | "302" | "500";
      /**
       * Gacha type, returned by MiHoYo API
       */
      gacha_type: "100" | "200" | "301" | "302" | "400" | "500";
      /**
       * The internal ID of the item
       */
      item_id: string;
      /**
       * The number of items, usually 1, returned by MiHoYo API
       */
      count?: string;
      /**
       * The local time in the timezone of the item being drawn.This MUST BE THE String typed value captured intact from the gacha record webpage WITHOUT ANY CONVERTION TO ANY DATE TYPES. Any conversion of such can cause potential timezone mistakes if the device time zone differs from the server time zone, unless special treatments are applied by individual app devs.
       */
      time: string;
      /**
       * The name of the item, returned by MiHoYo API
       */
      name?: string;
      /**
       * The type of the item, returned by MiHoYo API
       */
      item_type?: string;
      /**
       * The rank of the item, returned by MiHoYo API
       */
      rank_type?: string;
      /**
       * The internal ID of the record, returned by MiHoYo API
       */
      id: string;
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  }[];
  hkrpg?: {
    /**
     * UID
     */
    uid: string | number;
    /**
     * Time zone offset
     */
    timezone: number;
    /**
     * Language code
     */
    lang?:
      | "de-de"
      | "en-us"
      | "es-es"
      | "fr-fr"
      | "id-id"
      | "it-it"
      | "ja-jp"
      | "ko-kr"
      | "pt-pt"
      | "ru-ru"
      | "th-th"
      | "tr-tr"
      | "vi-vn"
      | "zh-cn"
      | "zh-tw";
    list: {
      /**
       * Gacha Pool ID
       */
      gacha_id: string;
      /**
       * Gacha type
       */
      gacha_type: "1" | "2" | "11" | "12" | "21" | "22";
      /**
       * The internal ID of the item
       */
      item_id: string;
      /**
       * The number of items, usually 1, returned by MiHoYo API
       */
      count?: string;
      /**
       * The local time in the timezone of the item being drawn.This MUST BE THE String typed value captured intact from the gacha record webpage WITHOUT ANY CONVERTION TO ANY DATE TYPES. Any conversion of such can cause potential timezone mistakes if the device time zone differs from the server time zone, unless special treatments are applied by individual app devs.
       */
      time: string;
      /**
       * The name of the item, returned by MiHoYo API
       */
      name?: string;
      /**
       * The type of the item, returned by MiHoYo API
       */
      item_type?: string;
      /**
       * The rank of the item, returned by MiHoYo API
       */
      rank_type?: string;
      /**
       * The internal ID of the record, returned by MiHoYo API
       */
      id: string;
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  }[];
  nap?: {
    /**
     * UID
     */
    uid: string | number;
    /**
     * Time zone offset
     */
    timezone: number;
    /**
     * Language code
     */
    lang?:
      | "de-de"
      | "en-us"
      | "es-es"
      | "fr-fr"
      | "id-id"
      | "it-it"
      | "ja-jp"
      | "ko-kr"
      | "pt-pt"
      | "ru-ru"
      | "th-th"
      | "tr-tr"
      | "vi-vn"
      | "zh-cn"
      | "zh-tw";
    list: {
      /**
       * Gacha Pool ID
       */
      gacha_id?: string;
      /**
       * Gacha type
       */
      gacha_type: "1" | "2" | "3" | "5";
      /**
       * The internal ID of the item
       */
      item_id: string;
      /**
       * The number of items, usually 1, returned by MiHoYo API
       */
      count?: string;
      /**
       * The local time in the timezone of the item being drawn.This MUST BE THE String typed value captured intact from the gacha record webpage WITHOUT ANY CONVERTION TO ANY DATE TYPES. Any conversion of such can cause potential timezone mistakes if the device time zone differs from the server time zone, unless special treatments are applied by individual app devs.
       */
      time: string;
      /**
       * The name of the item, returned by MiHoYo API
       */
      name?: string;
      /**
       * The type of the item, returned by MiHoYo API
       */
      item_type?: string;
      /**
       * The rank of the item, returned by MiHoYo API
       */
      rank_type?: string;
      /**
       * The internal ID of the record, returned by MiHoYo API
       */
      id: string;
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  }[];
  hk4e_ugc?: unknown[];
  [k: string]: unknown;
}
